# Generated by Django 3.1.14 on 2022-03-09 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='address',
            field=models.ForeignKey(db_column='address_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='forecasting.address'),
        ),
    ]
