# Generated by Django 3.1.14 on 2022-02-05 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='large_category_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='medium_category_address',
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=13)),
                ('large_category_address', models.CharField(blank=True, choices=[('Seoul', '서울특별시'), ('Gyeonggi-do', '경기도')], max_length=15)),
                ('medium_category_address', models.CharField(blank=True, choices=[('Hwaseong-si', '화성시'), ('Suwon-si', '수원시'), ('Seongnam-si', '성남시'), ('Anyang-si', '안양시')], max_length=15)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
