# Generated by Django 3.1.14 on 2022-02-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='largecategoryaddress',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mediumcategoryaddress',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
