# Generated by Django 3.1.14 on 2022-02-20 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'crop',
                'ordering': ['-code'],
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'farm',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LargeCategoryAddress',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'large_category_address',
                'ordering': ['-code'],
            },
        ),
        migrations.CreateModel(
            name='MediumCategoryAddress',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'medium_category_address',
                'ordering': ['-code'],
            },
        ),
        migrations.CreateModel(
            name='ProducingCrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_in_house', models.BooleanField(default=False)),
                ('crop', models.ForeignKey(db_column='crop_code', on_delete=django.db.models.deletion.CASCADE, related_name='producing_crop_set', to='forecasting.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producing_crop_set', to='forecasting.farm')),
            ],
            options={
                'db_table': 'producing_crop',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Forecasting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('target', models.CharField(blank=True, max_length=16)),
                ('crop', models.ForeignKey(db_column='crop_code', on_delete=django.db.models.deletion.CASCADE, to='forecasting.crop')),
                ('medium_category_address', models.ForeignKey(db_column='medium_category_address_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='forecasting.mediumcategoryaddress')),
            ],
            options={
                'db_table': 'forecasting',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='farm',
            name='large_category_address',
            field=models.ForeignKey(db_column='large_category_address_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='forecasting.largecategoryaddress'),
        ),
        migrations.AddField(
            model_name='farm',
            name='medium_category_address',
            field=models.ForeignKey(db_column='medium_category_address_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='forecasting.mediumcategoryaddress'),
        ),
        migrations.AddField(
            model_name='farm',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
