# Generated by Django 3.1.14 on 2022-02-14 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('forecasting', '0001_initial'), ('forecasting', '0002_auto_20220209_2343'), ('forecasting', '0003_remove_farm_name'), ('forecasting', '0004_auto_20220212_0101')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('name', models.CharField(max_length=16)),
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'crop',
                'ordering': ['-code'],
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large_category_address', models.CharField(blank=True, choices=[('서울특별시', '서울특별시'), ('경기도', '경기도')], max_length=15)),
                ('medium_category_address', models.CharField(blank=True, choices=[('화성시', '화성시'), ('수원시', '수원시'), ('성남시', '성남시'), ('안양시', '안양시'), ('가평군', '가평군')], max_length=15)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'farm',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Forecasting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('sigungu_code', models.CharField(blank=True, max_length=16)),
                ('sigungu_name', models.CharField(blank=True, max_length=16)),
                ('crop_name', models.CharField(blank=True, max_length=16)),
                ('crop_code', models.CharField(blank=True, max_length=16)),
                ('target', models.CharField(blank=True, max_length=16)),
            ],
            options={
                'db_table': 'forecasting',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProducingCrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_in_house', models.BooleanField(default=False)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producing_crop_set', to='forecasting.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producing_crop_set', to='forecasting.farm')),
            ],
            options={
                'db_table': 'producing_crop',
                'ordering': ['-id'],
            },
        ),
    ]
