# Generated by Django 3.1.14 on 2022-02-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecasting',
            name='area_ratio',
        ),
        migrations.RemoveField(
            model_name='forecasting',
            name='damage_rate',
        ),
        migrations.RemoveField(
            model_name='forecasting',
            name='generated_area',
        ),
        migrations.RemoveField(
            model_name='forecasting',
            name='susceptibility',
        ),
    ]
