# Generated by Django 3.1.14 on 2022-02-10 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0002_auto_20220209_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='name',
        ),
    ]
