# Generated by Django 3.1.14 on 2022-02-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0003_remove_farm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='large_category_address',
            field=models.CharField(blank=True, choices=[('서울특별시', '서울특별시'), ('경기도', '경기도')], max_length=15),
        ),
        migrations.AlterField(
            model_name='farm',
            name='medium_category_address',
            field=models.CharField(blank=True, choices=[('화성시', '화성시'), ('수원시', '수원시'), ('성남시', '성남시'), ('안양시', '안양시'), ('가평군', '가평군')], max_length=15),
        ),
    ]
